chore: updating dependabot file to support gha, TS, JS, gradle, Go lang, cargo and docker packages
rajpalc7/indy-vdr pull request #1
Opened 2024-05-07 19:21 UTC by rajpalc7

2024-05-07 19:31 UTC, rajpalc7 commented
Hi @wadeBarnes, this is ready for review now.

2024-05-09 13:47 UTC, WadeBarnes requested changes
Have a closer look at how this `rust` project is setup.  It looks like it's setup with workspaces.  Before making any changes, verify Dependabot supports this for `rust` the same way it supports it for `npm`/`yarn`.

2024-05-09 18:54 UTC, rajpalc7 commented
Thanks @WadeBarnes , I have made the changes as per your suggestion.

2024-05-10 14:08 UTC, WadeBarnes approved these changes

2024-05-17 16:16 UTC, closed without merging